### ISSUE TITLE
problem with node "response"

### ISSUE THREAD

**Issue by EnelAbba** [sinricpro/node-red-contrib-sinric-pro#6]
Hi
I created 10 nodes with SinricPro, connected to ESP32 devices. I use node-red to connect Sinric Pro to hardware devices. I command these devices through some echo-pops and echo-dots, using SinricPro. The system worked for about 2 months, but now there is a problem. Every time I communicate a command to Alexa, the system works correctly only in the first phase. For example, if I say "Alexa, turn on the light", Alexa turns on the light. Unfortunately after about 20 seconds, echo-pop tells me that "the device is not responding". On node-red, the "response" node seems to work correctly because immediately after the command, the "sent" message appears under the node.
It seems that when the message from node-red comes back to the server, something is wrong.
I would like to point out that the system worked correctly for about 2 months and that I did not make any code changes or updates.
I use sinricpro/node-red-contrib-sinric-pro version 1.4.1.
If I enter the Alexa App, select one of my devices connected to SinricPro (in the settings menu you can see that the device is connected to Sinric Pro), and press the turn on button, the lamp turns on, but after a few seconds at the top of the page the message "the device is not responding" appears in the app
I tried to turn a device not connected to SInric Pro on and off through the Alexa App; in this case everything works correctly.

**Comment by kakopappa** [comment]
Hi,

1. Do you see any errors in the Portal -> Activity Log?
2. Please contact support with the device id.

**Comment by kakopappa** [comment]
Hi @EnelAbba 

Found the issue and fixed it. Please update the library to 1.5.1. 

sorry about the inconvince caused

**Comment by EnelAbba** [comment]
Thanks
everything works perfectly
